<?PHP
	/* Automatically Generated By X7 Chat 2 Installer :: 7:34:24 Sep 03, 2007 */
	$X7CHAT_CONFIG['DB_USERNAME'] = "x7chat";
	$X7CHAT_CONFIG['DB_PASSWORD'] = "";
	$X7CHAT_CONFIG['DB_HOST'] = "localhost";
	$X7CHAT_CONFIG['DB_NAME'] = "x7chat";
	$X7CHAT_CONFIG['DB_TYPE'] = "mysql";
	$prefix = "x7chat2_";
	$X7CHAT_CONFIG['AUTH_MODE'] = "md5";
	$X7CHAT_CONFIG['COOKIE_PATH'] = "/";
	$X7CHAT_CONFIG['USE_PCONNECT'] = 0;
	$X7CHAT_CONFIG['DISABLE_XUPDATER'] = 0;
	$X7CHAT_CONFIG['INSTALLED'] = 1;
	$X7CHATVERSION = "2.0.5";

	// These can be uncommented for debugging
	//$DEBUG_JAVASCRIPT = "";

	// MUSE Support
	// $MUSE_DB['current'] = 1;
	// $MUSE_DB['user_1'] = "";
	// $MUSE_DB['pass_1'] = "";
	// $MUSE_DB['user_2'] = "";
	// $MUSE_DB['pass_2'] = "";

?>